import Link from "next/link";
import { requireAdmin } from "@/lib/session";
import { prisma } from "@/lib/db";
import { adminExpressAction } from "@/lib/actions/delivery";

export const metadata = { title: "Express administration" };
export default async function AdminExpressPage() {
  await requireAdmin();
  const [config, sellers, pickups, deliveries, webhookFailures] = await Promise.all([
    prisma.expressConfiguration.findUnique({ where: { id: "global" } }),
    prisma.sellerProfile.findMany({ include: { deliverySettings: true } }),
    prisma.pickupLocation.findMany({ include: { seller: true }, orderBy: { createdAt: "desc" } }),
    prisma.delivery.findMany({ include: { seller: true, order: true, providerConfig: true, history: { orderBy: { createdAt: "asc" } } }, orderBy: { updatedAt: "desc" }, take: 100 }),
    prisma.deliveryWebhookEvent.findMany({ where: { processingError: { not: null } }, include: { providerConfig: true }, orderBy: { receivedAt: "desc" }, take: 30 }),
  ]);
  return <div className="wt-container py-10"><p className="text-xs uppercase tracking-[.16em] text-[var(--copper)]">Administration</p><h1 className="mt-2 font-sans text-4xl font-semibold">WineBloom Express monitor</h1><p className="mt-2 text-[var(--ink-soft)]">Express and alcohol delivery remain disabled until explicitly approved here.</p>
    <section className="mt-8 rounded-2xl border border-[var(--line)] bg-white/50 p-6"><h2 className="font-display text-2xl">Pilot controls</h2><form action={adminExpressAction} className="mt-4 grid gap-4 sm:grid-cols-2"><input type="hidden" name="intent" value="global"/><label className="flex gap-2"><input type="checkbox" name="enabled" defaultChecked={config?.enabled}/> Enable Express globally</label><label className="flex gap-2"><input type="checkbox" name="alcoholEnabled" defaultChecked={config?.alcoholEnabled}/> Enable configured alcohol jurisdictions</label><label className="wt-label sm:col-span-2">Allowed country codes (comma-separated)<input className="wt-input" name="allowedCountries" defaultValue={config?.allowedCountriesCsv ?? ""}/></label><button className="wt-btn wt-btn-primary sm:col-span-2">Save pilot controls</button></form></section>
    <h2 className="mt-10 font-display text-2xl">Seller approvals</h2><div className="mt-4 grid gap-3">{sellers.map(s=><form action={adminExpressAction} key={s.id} className="flex flex-wrap items-end gap-3 rounded-2xl border border-[var(--line)] bg-white/50 p-5"><input type="hidden" name="intent" value="seller"/><input type="hidden" name="sellerId" value={s.id}/><p className="mr-auto font-semibold">{s.displayName}</p><label className="wt-label">Express<select className="wt-select" name="approval" defaultValue={s.deliverySettings?.adminApprovalStatus ?? "PENDING"}><option>PENDING</option><option>APPROVED</option><option>SUSPENDED</option></select></label><label className="wt-label">Alcohol<select className="wt-select" name="alcoholApproval" defaultValue={s.deliverySettings?.alcoholApprovalStatus ?? "NOT_APPROVED"}><option>NOT_APPROVED</option><option>APPROVED</option><option>SUSPENDED</option></select></label><button className="wt-btn wt-btn-secondary !py-2">Save</button></form>)}</div>
    <h2 className="mt-10 font-display text-2xl">Pickup approvals</h2><div className="mt-4 grid gap-3">{pickups.map(p=><form action={adminExpressAction} key={p.id} className="flex items-center justify-between gap-3 rounded-2xl border border-[var(--line)] bg-white/50 p-5"><input type="hidden" name="intent" value="pickup"/><input type="hidden" name="pickupId" value={p.id}/><p>{p.seller.displayName} · {p.address1}, {p.postalCode} {p.city}</p><button name="approved" value={p.approved ? "false" : "true"} className="wt-btn wt-btn-secondary !py-2">{p.approved ? "Suspend" : "Approve"}</button></form>)}</div>
    <h2 className="mt-10 font-display text-2xl">Active and recent deliveries</h2><div className="mt-4 grid gap-3">{deliveries.map(d=><Link href={`/orders/${d.orderId}`} key={d.id} className="rounded-2xl border border-[var(--line)] bg-white/50 p-5"><p className="font-semibold">{d.seller.displayName} · {d.status.replaceAll("_", " ")}</p><p className="text-sm text-[var(--ink-soft)]">{d.providerConfig.displayName} · reference {d.providerDeliveryId ?? "not dispatched"} · updated {d.updatedAt.toLocaleString()}</p>{d.failureCategory&&<p className="mt-2 text-sm text-[var(--danger)]">{d.failureCategory}: {d.customerExplanation}</p>}</Link>)}{!deliveries.length&&<p>No deliveries.</p>}</div>
    {webhookFailures.length>0&&<><h2 className="mt-10 font-display text-2xl">Webhook processing review</h2><div className="mt-4 grid gap-2 text-sm">{webhookFailures.map(e=><p key={e.id}>{e.providerConfig.displayName} · {e.providerEventId} · {e.processingError}</p>)}</div></>}
  </div>;
}
