"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/db";
import { requireSeller } from "@/lib/session";
import { slugify } from "@/lib/utils";

function parseCsv(text:string){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(lines.length<2)return [];const split=(line:string)=>line.split(/,(?=(?:[^\"]*\"[^\"]*\")*[^\"]*$)/).map(x=>x.trim().replace(/^\"|\"$/g,"").replace(/\"\"/g,'"'));const headers=split(lines[0]).map(x=>x.toLowerCase().replace(/[^a-z0-9]+/g,""));return lines.slice(1,101).map(line=>Object.fromEntries(split(line).map((v,i)=>[headers[i],v])))}
export async function importListingDraftsAction(formData:FormData){const {seller}=await requireSeller();const file=formData.get("inventory");if(!(file instanceof File)||file.size>2_000_000||!file.name.toLowerCase().endsWith(".csv"))redirect("/sell/assistant?error=file");const rows=parseCsv(await file.text());if(!rows.length)redirect("/sell/assistant?error=empty");for(const row of rows){const title=row.title||row.product||row.name||"Untitled item";const price=Number(row.price||row.unitprice);const quantity=Number(row.quantity||row.qty);const vintage=Number(row.vintage||row.year);const duplicate=await prisma.listing.findFirst({where:{sellerId:seller.id,title:{equals:title}}});const missing=[!title||title==="Untitled item"?"title":"",!Number.isFinite(price)?"price":"",!Number.isFinite(quantity)?"quantity":"",!row.description?"description":""].filter(Boolean);await prisma.listingDraft.create({data:{sellerId:seller.id,createdById:seller.userId,sourceName:file.name,title,description:row.description||`Seller-provided inventory item: ${title}. Review and complete this description before publishing.`,category:row.category||null,priceCents:Number.isFinite(price)?Math.round(price*100):null,quantity:Number.isFinite(quantity)?Math.max(0,Math.floor(quantity)):null,vintage:Number.isFinite(vintage)?vintage:null,producer:row.producer||row.brand||null,bottleSizeMl:Number(row.bottlesizeml)||null,missingFieldsCsv:missing.join(","),confidence:Math.max(.2,1-missing.length*.2-(duplicate?.2:0)),duplicateListingId:duplicate?.id,status:missing.length||duplicate?"NEEDS_REVIEW":"READY_FOR_APPROVAL"}})}await prisma.auditLog.create({data:{actorId:seller.userId,action:"AI_LISTING_DRAFTS_IMPORTED",meta:JSON.stringify({sellerId:seller.id,fileName:file.name,rowCount:rows.length})}});revalidatePath("/sell/assistant");redirect("/sell/assistant?ok=imported")}
export async function approveListingDraftAction(formData:FormData){const {seller}=await requireSeller();const id=String(formData.get("draftId"));const draft=await prisma.listingDraft.findFirst({where:{id,sellerId:seller.id}});if(!draft||draft.missingFieldsCsv||draft.duplicateListingId||draft.priceCents==null||draft.quantity==null)redirect("/sell/assistant?error=review");let slug=slugify(draft.title);if(await prisma.listing.findUnique({where:{slug}}))slug+=`-${Date.now().toString(36)}`;await prisma.$transaction([prisma.listing.create({data:{sellerId:seller.id,title:draft.title,slug,description:draft.description,priceCents:draft.priceCents,quantity:draft.quantity,currency:draft.currency,status:"DRAFT",searchText:[draft.title,draft.description,draft.producer,draft.vintage].filter(Boolean).join(" ").toLowerCase()}}),prisma.listingDraft.update({where:{id},data:{status:"APPROVED_AND_CREATED"}}),prisma.auditLog.create({data:{actorId:seller.userId,action:"AI_LISTING_DRAFT_APPROVED",meta:JSON.stringify({draftId:id,sellerId:seller.id})}})]);revalidatePath("/sell/assistant");revalidatePath("/sell/listings");redirect("/sell/listings")}
