"use client";
import { useState } from "react";
import Link from "next/link";

type Mode = "BUYER" | "SELLER" | "SUPPORT";
type Reply = { answer:string; mode:Mode; results:{id:string;title:string;priceCents:number;currency:string;seller:string;url:string}[]; citations:{label:string;href:string}[]; escalated:boolean; conversationId:string };
export function MarketplaceAssistant({ initialMode = "BUYER", sellerEnabled = false }: { initialMode?: Mode; sellerEnabled?: boolean }) {
  const [mode,setMode]=useState<Mode>(initialMode); const [message,setMessage]=useState(""); const [reply,setReply]=useState<Reply|null>(null); const [conversationId,setConversationId]=useState<string>(); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const res=await fetch("/api/assistant",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({message,mode,conversationId})});const data=await res.json();if(!res.ok)throw new Error(data.error||"Assistant unavailable");setReply(data);setConversationId(data.conversationId);}catch(e){setError(e instanceof Error?e.message:"Assistant unavailable");}finally{setBusy(false)}}
  return <div className="grid gap-6 lg:grid-cols-[minmax(0,1fr)_22rem]"><section className="rounded-3xl border border-[var(--line)] bg-white/55 p-6"><div className="flex flex-wrap gap-2" role="tablist" aria-label="Assistant mode">{(["BUYER","SUPPORT",...(sellerEnabled?["SELLER" as const]:[])] as Mode[]).map(x=><button key={x} type="button" onClick={()=>setMode(x)} className={`wt-btn !py-2 text-sm ${mode===x?"wt-btn-primary":"wt-btn-secondary"}`}>{x.charAt(0)+x.slice(1).toLowerCase()}</button>)}</div><p className="mt-5 text-sm text-[var(--ink-soft)]">{mode==="BUYER"?"Ask naturally. I only return currently available WineTreff offers.":mode==="SUPPORT"?"Ask about approved WineTreff policies. Account-specific or uncertain issues go to support.":"Prepare seller-owned listing drafts. Nothing publishes without your approval."}</p><form onSubmit={submit} className="mt-4"><label className="wt-label">Message<textarea className="wt-textarea min-h-32" value={message} onChange={e=>setMessage(e.target.value)} placeholder={mode==="BUYER"?"Find a collectible Scotch under €500 for a retirement gift":mode==="SUPPORT"?"How do seller fees work?":"Help me prepare inventory listings"} required minLength={2} maxLength={2000}/></label><button disabled={busy} className="wt-btn wt-btn-primary mt-4 disabled:opacity-60">{busy?"Thinking…":"Ask WineTreff AI"}</button></form>{error&&<p className="mt-4 text-sm text-[var(--danger)]">{error}</p>}{reply&&<div className="mt-6 border-t border-[var(--line)] pt-6" aria-live="polite"><p className="whitespace-pre-wrap">{reply.answer}</p>{reply.results.length>0&&<div className="mt-5 grid gap-3">{reply.results.map(x=><Link key={x.id} href={x.url} className="rounded-xl border border-[var(--line)] p-4 hover:bg-white"><p className="font-semibold">{x.title}</p><p className="text-sm text-[var(--ink-soft)]">{x.seller} · {new Intl.NumberFormat(undefined,{style:"currency",currency:x.currency.toUpperCase()}).format(x.priceCents/100)}</p></Link>)}</div>}{reply.citations.length>0&&<p className="mt-5 text-sm">Sources: {reply.citations.map((x,i)=><span key={x.href}>{i>0&&" · "}<Link className="underline" href={x.href}>{x.label}</Link></span>)}</p>}{reply.escalated&&<a href="mailto:support@winetreff.com" className="wt-btn wt-btn-secondary mt-5">Contact human support</a>}</div>}</section><aside className="rounded-3xl border border-[var(--line)] bg-[rgba(31,61,50,.06)] p-6"><h2 className="font-display text-xl">How I work</h2><ul className="mt-4 space-y-3 text-sm text-[var(--ink-soft)]"><li>✓ Search live, in-stock seller offers</li><li>✓ Cite WineTreff policy pages</li><li>✓ Keep seller claims attributable to sellers</li><li>✓ Escalate disputes and authenticity questions</li><li>✕ Never invent price, availability, provenance, rarity, or guarantees</li></ul><p className="mt-5 text-xs text-[var(--ink-soft)]">You are interacting with AI. Verify product details on the seller’s listing before purchase.</p></aside></div>;
}
