import Link from "next/link";
import { requireSeller } from "@/lib/session";
import { prisma } from "@/lib/db";
import { addPickupLocationAction, saveSellerDeliverySettingsAction, sellerDeliveryAction } from "@/lib/actions/delivery";

export const metadata = { title: "WineBloom Express" };
export default async function SellerExpressPage() {
  const { seller } = await requireSeller();
  const [settings, pickups, deliveries] = await Promise.all([
    prisma.sellerDeliverySettings.findUnique({ where: { sellerId: seller.id } }),
    prisma.pickupLocation.findMany({ where: { sellerId: seller.id }, orderBy: { createdAt: "desc" } }),
    prisma.delivery.findMany({ where: { sellerId: seller.id }, include: { order: { include: { items: true } }, history: { orderBy: { createdAt: "asc" } } }, orderBy: { createdAt: "desc" }, take: 50 }),
  ]);
  return <div className="wt-container py-10"><p className="text-xs uppercase tracking-[.16em] text-[var(--copper)]">Seller tools</p><h1 className="mt-2 font-sans text-4xl font-semibold">WineBloom Express</h1><p className="mt-2 max-w-3xl text-[var(--ink-soft)]">Configure requests fulfilled by approved third-party couriers. You remain the seller of record and confirm inventory before any courier is requested.</p>
    <section className="mt-8 rounded-2xl border border-[var(--line)] bg-white/50 p-6"><h2 className="font-display text-2xl">Availability</h2><p className="mt-1 text-sm">Approval: {settings?.adminApprovalStatus ?? "PENDING"} · Alcohol: {settings?.alcoholApprovalStatus ?? "NOT_APPROVED"}</p><form action={saveSellerDeliverySettingsAction} className="mt-5 grid gap-4 sm:grid-cols-2"><Check name="expressEnabled" label="Request Express delivery" checked={settings?.expressEnabled}/><Check name="scheduledEnabled" label="Request scheduled delivery" checked={settings?.scheduledEnabled}/><Check name="acceptingLocalOrders" label="Currently accepting local orders" checked={settings?.acceptingLocalOrders}/><label className="wt-label">Timezone<input className="wt-input" name="timezone" defaultValue={settings?.timezone ?? "Europe/Berlin"} required/></label><label className="wt-label">Preparation time (minutes)<input className="wt-input" type="number" name="preparationMinutes" min="5" max="1440" defaultValue={settings?.preparationMinutes ?? 60}/></label><label className="wt-label">Delivery radius (km)<input className="wt-input" type="number" name="deliveryRadiusKm" min="0" max="500" step=".1" defaultValue={settings?.deliveryRadiusKm ?? 0}/></label><label className="wt-label">Minimum order (EUR)<input className="wt-input" type="number" name="minOrderEuros" min="0" step=".01" defaultValue={(settings?.minOrderCents ?? 0)/100}/></label><label className="wt-label">Maximum order (EUR)<input className="wt-input" type="number" name="maxOrderEuros" min="0" step=".01" defaultValue={settings?.maxOrderCents ? settings.maxOrderCents/100 : ""}/></label><label className="wt-label sm:col-span-2">Courier pickup instructions<textarea className="wt-textarea" name="deliveryInstructions" defaultValue={settings?.deliveryInstructions ?? ""}/></label><button className="wt-btn wt-btn-primary sm:col-span-2">Save settings</button></form></section>
    <section className="mt-6 rounded-2xl border border-[var(--line)] bg-white/50 p-6"><h2 className="font-display text-2xl">Pickup locations</h2><div className="mt-3 grid gap-2 text-sm">{pickups.map(p=><p key={p.id}>{p.label}: {p.address1}, {p.postalCode} {p.city} · {p.approved ? "Approved" : "Awaiting admin approval"}</p>)}</div><form action={addPickupLocationAction} className="mt-5 grid gap-3 sm:grid-cols-2"><input className="wt-input" name="label" placeholder="Location name" required/><input className="wt-input" name="address1" placeholder="Street address" required/><input className="wt-input" name="address2" placeholder="Address line 2"/><input className="wt-input" name="city" placeholder="City" required/><input className="wt-input" name="region" placeholder="State / region"/><input className="wt-input" name="postalCode" placeholder="Postal code" required/><input className="wt-input" name="country" placeholder="Country code" maxLength={2} required/><button className="wt-btn wt-btn-secondary">Add for approval</button></form></section>
    <section className="mt-8"><h2 className="font-display text-2xl">Delivery requests</h2><div className="mt-4 grid gap-4">{deliveries.map(d=><article key={d.id} className="rounded-2xl border border-[var(--line)] bg-white/50 p-5"><div className="flex flex-wrap justify-between gap-3"><div><Link className="font-semibold underline" href={`/orders/${d.orderId}`}>{d.order.items.map(i=>i.title).join(", ")}</Link><p className="text-sm text-[var(--ink-soft)]">{d.status.replaceAll("_", " ")} · {d.fulfillmentType}</p></div><form action={sellerDeliveryAction} className="flex flex-wrap gap-2"><input type="hidden" name="deliveryId" value={d.id}/>{d.status==="awaiting_seller_acceptance"&&<><button className="wt-btn wt-btn-primary !py-2" name="intent" value="accept">Confirm inventory & accept</button><button className="wt-btn wt-btn-secondary !py-2" name="intent" value="reject">Reject</button></>}{d.status==="seller_accepted"&&<button className="wt-btn wt-btn-secondary !py-2" name="intent" value="prepare">Start preparing</button>}{["seller_accepted","preparing"].includes(d.status)&&<button className="wt-btn wt-btn-primary !py-2" name="intent" value="ready">Ready for pickup</button>}{d.status==="ready_for_pickup"&&<button className="wt-btn wt-btn-primary !py-2" name="intent" value="dispatch">Request courier</button>}</form></div><ol className="mt-4 space-y-1 text-sm">{d.history.map(h=><li key={h.id}>{h.createdAt.toLocaleString()} — {h.toStatus.replaceAll("_", " ")}</li>)}</ol></article>)}{!deliveries.length&&<p className="text-[var(--ink-soft)]">No Express requests yet.</p>}</div></section></div>;
}
function Check({name,label,checked}:{name:string;label:string;checked?:boolean}) { return <label className="flex items-center gap-2 text-sm"><input type="checkbox" name={name} defaultChecked={checked}/>{label}</label>; }
