import { notFound } from "next/navigation";
import { prisma } from "@/lib/db";
import { requireAgeVerified } from "@/lib/session";
import { formatEur } from "@/lib/commerce/fees";
import { requestDeliveryQuoteAction } from "@/lib/actions/delivery";
import { startCheckoutAction } from "@/lib/actions/marketplace";

export default async function FulfillmentPage({ params, searchParams }: { params: Promise<{listingId:string}>, searchParams: Promise<{quote?:string,error?:string}> }) {
  await requireAgeVerified(); const { listingId } = await params; const sp = await searchParams;
  const listing = await prisma.listing.findFirst({ where: { id: listingId, status: "ACTIVE" }, include: { seller: { include: { deliverySettings: true, pickupLocations: { where: { approved: true, active: true } } } } } }); if (!listing) notFound();
  const quote = sp.quote ? await prisma.deliveryQuote.findFirst({ where: { id: sp.quote, sellerId: listing.sellerId } }) : null;
  const standardBuy = startCheckoutAction.bind(null, listing.id, undefined); const expressBuy = quote ? startCheckoutAction.bind(null, listing.id, quote.id) : undefined;
  return <div className="wt-container py-10"><p className="text-xs uppercase tracking-[.16em] text-[var(--copper)]">Checkout · {listing.seller.displayName}</p><h1 className="mt-2 font-sans text-4xl font-semibold">Choose fulfillment</h1><p className="mt-2 text-[var(--ink-soft)]">Each seller fulfills separately. WineTreff facilitates the transaction; the seller owns and prepares the inventory.</p>{sp.error&&<p className="mt-4 rounded-xl bg-[rgba(139,46,46,.1)] p-4 text-sm text-[var(--danger)]">Express is unavailable or the quote expired. Check the address and current seller eligibility, then request a new quote.</p>}
    <div className="mt-8 grid gap-5 lg:grid-cols-2"><section className="rounded-2xl border border-[var(--line)] bg-white/50 p-6"><h2 className="font-display text-2xl">Standard shipping</h2><p className="mt-2 text-sm text-[var(--ink-soft)]">Seller-managed shipping · {formatEur(listing.shippingCents)}</p><form action={standardBuy} className="mt-5"><button className="wt-btn wt-btn-secondary">Continue to payment</button></form></section>
    <section className="rounded-2xl border border-[var(--line)] bg-white/50 p-6"><h2 className="font-display text-2xl">WineTreff Express</h2>{quote&&quote.expiresAt>new Date()?<><dl className="mt-3 grid gap-2 text-sm"><div><dt className="font-semibold">Delivery fee</dt><dd>{formatEur(quote.feeCents)}</dd></div><div><dt className="font-semibold">Estimated arrival</dt><dd>{quote.deliveryEta.toLocaleString()}</dd></div><div><dt className="font-semibold">Quote expires</dt><dd>{quote.expiresAt.toLocaleTimeString()}</dd></div></dl>{quote.ageVerification&&<p className="mt-4 rounded-xl bg-[rgba(176,138,90,.15)] p-4 text-sm">Valid ID and an eligible recipient are required in person. No contactless delivery. Failed delivery defaults to return-to-seller; refund responsibility may require support review.</p>}<form action={expressBuy} className="mt-5"><label className="mb-4 flex gap-2 text-sm"><input type="checkbox" required/> I acknowledge the age, presence, and failed-delivery terms.</label><button className="wt-btn wt-btn-primary">Accept quote & continue</button></form></>:<form action={requestDeliveryQuoteAction} className="mt-4 grid gap-3"><input type="hidden" name="listingId" value={listing.id}/><label className="wt-label">Service<input className="wt-input" name="fulfillmentType" value="EXPRESS" readOnly/></label><input className="wt-input" name="name" placeholder="Recipient name" required/><input className="wt-input" name="address1" placeholder="Street address" required/><input className="wt-input" name="address2" placeholder="Address line 2"/><div className="grid gap-3 sm:grid-cols-2"><input className="wt-input" name="city" placeholder="City" required/><input className="wt-input" name="region" placeholder="State / region"/><input className="wt-input" name="postalCode" placeholder="Postal code" required/><input className="wt-input" name="country" placeholder="Country code" maxLength={2} required/></div><input className="wt-input" name="phone" placeholder="Phone for courier (optional)"/><button className="wt-btn wt-btn-primary">Get live quote</button></form>}</section></div>
    <p className="mt-6 text-sm text-[var(--ink-soft)]">Seller pickup and scheduled delivery are configurable pilot options. Contact the seller if they are not shown.</p></div>;
}
